server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username:
    password:
    queues:
      text-message-update: text_message_update
      doc-message-update: doc_message_update
      photo-message-update: photo_message_update
      answer-message: answer_message
      registration-mail: registration_mail
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username:
    password:
  jpa:
    generate-ddl: true

token:
service:
  file_info:
    url: https://api.telegram.org/bot{token}/getFile?file_id={fileId}
  file_storage:
    url: https://api.telegram.org/file/bot{token}/{filePath}

link:
  address: 127.0.0.1:8082

salt:
